### ISSUE TITLE
Serialization of atoms with msgpack causes exception

### ISSUE THREAD

**Issue by wcreek** [bwegh/wamper#1]
For example:
wamper_protocol:serialize(ok, raw_msgpack). 
*\* exception error: bad argument: ok

Replacing a line https://github.com/bwegh/wamper/blob/master/src/wamper_protocol.erl#L142
with
    Enc = case msgpack:pack(Message, [{format,map}, {allow_atom, pack}]) of
seems to resolve the issue.

**Comment by bwegh** [comment]
I do understand your point of view @wcreek , yet do not see that as an issue.

It will keep you from sending messages that might be ment for internal use only, which should be any message still containing atoms (e.g. having payload from your middleware are entrance to the one checking the message before sending it out) .

In the callback erwa_middleware:check_out_message/2 you could alter all the atoms to valid binaries.

If you have an Idea how to easily forward the flag to allow serialization of atoms I will gladfully add it.

thanks for your feedback.
